version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - backend-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: message_app
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - backend-network

volumes:
    dbdata:

networks:
    backend-network:
        driver: bridge
